{
 "title": "Stellar Validators Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Latest Ledger Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sequence Number",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by(value) (validator_bias_latest_ledger_closed{job=\"validator\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "validator_bias_latest_ledger_closed",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Operation Breakdown (By Type)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Operation Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(name) (validator_bias_total_operations_sum{job=\"validator\"}) / sum by(name) (validator_bias_total_operations_count{job=\"validator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Claimable Balances Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum by(name) (validator_bias_operations_by_category_sum{job=\"validator\", category=\"Claimable Balances\"}) / sum by(name) (validator_bias_operations_by_category_count{job=\"validator\", category=\"Claimable Balances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Soroban Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum by(name) (validator_bias_operations_by_category_sum{job=\"validator\", category=\"Soroban\"}) / sum by(name) (validator_bias_operations_by_category_count{job=\"validator\", category=\"Soroban\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sponsorship Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(name) (validator_bias_operations_by_category_sum{job=\"validator\", category=\"Sponsorship\"}) / sum by(name) (validator_bias_operations_by_category_count{job=\"validator\", category=\"Sponsorship\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offers And AMMs Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "sum by(name) (validator_bias_operations_by_category_sum{job=\"validator\", category=\"Offers and AMMs\"}) / sum by(name) (validator_bias_operations_by_category_count{job=\"validator\", category=\"Offers and AMMs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "sum by(name) (validator_bias_operations_by_category_sum{job=\"validator\", category=\"Payments\"}) / sum by(name) (validator_bias_operations_by_category_count{job=\"validator\", category=\"Payments\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(name) (validator_bias_operations_by_category_sum{job=\"validator\", category=\"Other\"}) / sum by(name) (validator_bias_operations_by_category_count{job=\"validator\", category=\"Other\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stellar Development Foundation (By Node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "Total Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(node_id) (validator_bias_total_operations_sum{job=\"validator\", name=\"Stellar Development Foundation\"}) / sum by(node_id) (validator_bias_total_operations_count{job=\"validator\", name=\"Stellar Development Foundation\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 33 },
   "targets": [
    {
     "expr": "sum by(node_id, category) (validator_bias_operations_by_category_sum{job=\"validator\", name=\"Stellar Development Foundation\"}) / sum by(node_id, category) (validator_bias_operations_by_category_count{job=\"validator\", name=\"Stellar Development Foundation\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}