{
 "title": "Stellar Validators Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Latest Ledger Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sequence Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by(value) (validator_bias_latest_ledger_closed{job=\"validator\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "validator_bias_latest_ledger_closed",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Operation Breakdown (By Type)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Operation Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(name) (rate(validator_bias_total_operations_sum{job=\"validator\"}[$__rate_interval])) / sum by(name) (rate(validator_bias_total_operations_count{job=\"validator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Soroban Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 6 },
   "targets": [
    {
     "expr": "sum by(name) (rate(validator_bias_operations_by_category_sum{job=\"validator\", category=\"soroban\"}[$__rate_interval])) / sum by(name) (rate(validator_bias_operations_by_category_count{job=\"validator\", category=\"soroban\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "sum by(name) (rate(validator_bias_operations_by_category_sum{job=\"validator\", category=\"payments\"}[$__rate_interval])) / sum by(name) (rate(validator_bias_operations_by_category_count{job=\"validator\", category=\"payments\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trust Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(name) (rate(validator_bias_operations_by_category_sum{job=\"validator\", category=\"trust\"}[$__rate_interval])) / sum by(name) (rate(validator_bias_operations_by_category_count{job=\"validator\", category=\"trust\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Claimable Balances Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 14 },
   "targets": [
    {
     "expr": "sum by(name) (rate(validator_bias_operations_by_category_sum{job=\"validator\", category=\"claimable_balances\"}[$__rate_interval])) / sum by(name) (rate(validator_bias_operations_by_category_count{job=\"validator\", category=\"claimable_balances\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offers And AMMs Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 14 },
   "targets": [
    {
     "expr": "sum by(name) (rate(validator_bias_operations_by_category_sum{job=\"validator\", category=\"offers_and_AMMs\"}[$__rate_interval])) / sum by(name) (rate(validator_bias_operations_by_category_count{job=\"validator\", category=\"offers_and_AMMs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sponsorship Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(name) (rate(validator_bias_operations_by_category_sum{job=\"validator\", category=\"sponsorship\"}[$__rate_interval])) / sum by(name) (rate(validator_bias_operations_by_category_count{job=\"validator\", category=\"sponsorship\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 22 },
   "targets": [
    {
     "expr": "sum by(name) (rate(validator_bias_operations_by_category_sum{job=\"validator\", category=\"other\"}[$__rate_interval])) / sum by(name) (rate(validator_bias_operations_by_category_count{job=\"validator\", category=\"other\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stellar Development Foundation (By Node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "Total Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by(node_id) (rate(validator_bias_total_operations_sum{job=\"validator\", name=\"Stellar Development Foundation\"}[$__rate_interval])) / sum by(node_id) (rate(validator_bias_total_operations_count{job=\"validator\", name=\"Stellar Development Foundation\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 31 },
   "targets": [
    {
     "expr": "sum by(node_id, category) (rate(validator_bias_operations_by_category_sum{job=\"validator\", name=\"Stellar Development Foundation\"}[$__rate_interval])) / sum by(node_id, category) (rate(validator_bias_operations_by_category_count{job=\"validator\", name=\"Stellar Development Foundation\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}